[package]
name = "twinleaf-tools"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
crossbeam = "0.8.4"
getopts = "0.2.21"
serialport = "4.5.1"
twinleaf = { version = "0.1.0", path = "../twinleaf" }
