[package]
name = "twinleaf-tools"
version = "1.1.0"
edition = "2021"
license = "MIT"
description = "Tools for the Twinleaf I/O protocol for reading data from Twinleaf quantum sensors." 
homepage = "https://twinleaf.com"
repository = "https://github.com/twinleaf/twinleaf-rust"
readme = "README.md"

[dependencies]
chrono = "0.4.38"
crossbeam = "0.8.4"
getopts = "0.2.21"
serialport = "4.5.1"
twinleaf = { version = "1.1.0", path = "../twinleaf" }
